
name: Jordan Evans

# Provide the name for all of your other GitHub repos that relate to this class.
# If I substitute your username and the repo name in a GitHub URL like this:
#    `https://github.com/YOUR_GITHUB_USERNAME/REPO_NAME`
# I should find your repository.
repo_names:
  - ATLAS-Personal-App 
  - 11-models-from-data 
  - UXUICriticism


10-ux-ui-criticism:
  - https://vimeo.com/756987721
  - https://vimeo.com/756993415


11-models-from-data:
  - https://github.com/jordanaevanz/11-models-from-data/tree/main/personal_project


project-check-in-1: https://github.com/jordanaevanz/ATLAS-ios-Fall-22/issues/2
